// <auto-generated />
namespace CRIMAS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_tables_for_dividend_management : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_tables_for_dividend_management));
        
        string IMigrationMetadata.Id
        {
            get { return "201608050905407_added_tables_for_dividend_management"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
